// jumantarareqi20/vto-wastra-adat-nusantara/vto-wastra-adat-nusantara-20baf3ed709083f9b408eb83c41429366d61c2b8/constants.ts

import type { ClothingItem } from './types';

export const clothingItems: ClothingItem[] = [
  {
    id: 'dayak',
    name: 'Baju Adat Dayak',
    origin: 'Kalimantan',
    description: 'Pakaian adat Suku Dayak (Sapei Sapaq & Ta\'a), kaya akan motif alam dan manik-manik yang melambangkan status dan keberanian.',
    imageUrl: '/assets/wastra-dayak.png',
    coordinates: { lat: -0.5, lng: 114.0 },
    sejarah: 'Pakaian ini (khususnya Sapei Sapaq untuk pria dan Ta\'a untuk wanita) berasal dari tradisi kuno Suku Dayak Kenyah. Dibuat dari bahan alam seperti kulit kayu (kain kapuak) dan dihiasi dengan manik-manik, bulu burung, dan taring binatang.',
    filosofi: 'Motif pada baju melambangkan hubungan dengan alam dan arwah leluhur. Bulu Burung Enggang (simbol kebesaran), taring macan (keberanian), dan motif aso (naga/anjing) adalah penolak bala. Jumlah hiasan menunjukkan status sosial dan pengalaman pemiliknya.',
    konteks: 'Dikenakan saat upacara adat besar, tarian perang, upacara penyambutan tamu agung, dan festival panen (Gawai Dayak). Saat ini juga menjadi simbol kebanggaan budaya.',
  },
  {
    id: 'minangkabau',
    name: 'Bundo Kanduang',
    origin: 'Sumatera Barat',
    description: 'Pakaian adat Minangkabau yang megah, melambangkan peran penting perempuan dalam adat matrilineal.',
    imageUrl: '/assets/wastra-minang.png',
    coordinates: { lat: -0.94, lng: 100.36 },
    sejarah: 'Juga dikenal sebagai "Limpapeh Rumah Nan Gadang", busana ini adalah pakaian kebesaran bagi wanita Minang yang telah menikah dan menjadi pemangku adat atau "Bundo Kanduang".',
    filosofi: 'Hiasan kepala (Tingkuluak Tanduk) melambangkan "Rumah Gadang" (rumah adat) dan kesetiaan pada adat. Pakaian ini adalah simbol kebijaksanaan, kepemimpinan, dan peran sentral perempuan sebagai penjaga harta pusaka dan penerus keturunan.',
    konteks: 'Dipakai oleh wanita pemangku adat (Bundo Kanduang) dalam upacara-upacara besar seperti penobatan, pernikahan adat, dan musyawarah adat.',
  },
  {
    id: 'bugis',
    name: 'Baju Bodo',
    origin: 'Sulawesi Selatan',
    description: 'Salah satu busana tertua di dunia, Baju Bodo dari Suku Bugis-Makassar memiliki warna yang menandakan usia dan status.',
    imageUrl: '/assets/wastra-bugis.png',
    coordinates: { lat: -4.5, lng: 120.0 },
    sejarah: 'Dipercaya sebagai salah satu busana tertua di dunia, telah ada sejak abad ke-9, awalnya dibuat dari kain tenun tipis (kain Muslin) yang didatangkan dari India dan Timur Tengah.',
    filosofi: 'Bentuknya yang longgar melambangkan kesopanan dan kebersahajaan. Warna pakaian memiliki aturan ketat: Jingga (anak-anak), Merah (gadis), Ungu (janda), Hijau (bangsawan), dan Putih (suci/pemuka agama).',
    konteks: 'Dulu adalah pakaian sehari-hari, kini Baju Bodo dikenakan untuk upacara pernikahan, tarian adat (seperti Tari Pakarena), dan acara-acara resmi kenegaraan atau kedaerahan.',
  },
  {
    id: 'bali',
    name: 'Payas Agung',
    origin: 'Bali',
    description: 'Busana adat Bali yang mewah dan agung, biasanya dikenakan saat upacara pernikahan atau potong gigi.',
    imageUrl: '/assets/wastra-bali.png',
    coordinates: { lat: -8.4, lng: 115.18 },
    sejarah: 'Pakaian kebesaran ini adalah warisan dari zaman kerajaan-kerajaan Bali kuno, yang dirancang untuk menunjukkan kemewahan dan status keluarga bangsawan.',
    filosofi: 'Pengantin yang mengenakan Payas Agung didandani layaknya "Raja dan Ratu sehari", menyerupai pakaian para dewa-dewi dalam mitologi Hindu. Hiasan emas dan mahkota yang menjulang tinggi (Gelung Agung) melambangkan kemakmuran dan keagungan.',
    konteks: 'Hanya digunakan untuk upacara paling penting, terutama upacara pernikahan (Mepandes) dan upacara potong gigi (Metatah) bagi keluarga bangsawan atau berkecukupan.',
  },
  {
    id: 'batak',
    name: 'Ulos Batak',
    origin: 'Sumatera Utara',
    description: 'Kain tenun Ulos yang menjadi simbol restu, kasih sayang, dan persatuan dalam masyarakat Batak.',
    imageUrl: '/assets/wastra-batak.png',
    coordinates: { lat: 2.5, lng: 99.0 },
    sejarah: 'Ulos adalah kain tenun yang ditenun secara manual oleh para wanita Batak dan telah menjadi bagian integral dari budaya Batak selama berabad-abad, diwariskan dari generasi ke generasi.',
    filosofi: 'Ulos dianggap sebagai "pemberi kehangatan" (baik secara harfiah maupun kiasan). Memberikan Ulos (Mangulosi) adalah simbol pemberian kasih sayang, doa restu, dan perlindungan. Setiap motif Ulos (seperti Ragidup atau Sadum) memiliki makna dan peruntukan yang berbeda.',
    konteks: 'Ulos sangat sentral dalam adat Batak. Diberikan saat peristiwa penting: kelahiran, pernikahan (diberikan oleh orang tua pengantin wanita), kematian (Ulos Saput), dan upacara adat lainnya.',
  },
  {
    id: 'jawa',
    name: 'Kebaya Jawa',
    origin: 'Jawa Tengah',
    description: 'Kebaya Jawa adalah busana anggun yang mencerminkan filosofi kesederhanaan dan kelembutan wanita Jawa.',
    imageUrl: '/assets/wastra-jawa.png',
    coordinates: { lat: -7.15, lng: 110.14 },
    sejarah: 'Berkembang dari busana era Kerajaan Majapahit, kemudian mendapat pengaruh dari budaya Tiongkok (baju atasan) dan Belanda (kain) hingga menjadi bentuknya yang sekarang. Menjadi populer di kalangan bangsawan dan rakyat.',
    filosofi: 'Melambangkan kelembutan, kesopanan, dan kepatuhan ("kewanitaan") wanita Jawa. Desainnya yang pas badan (namun tidak ketat) dipadukan dengan kain jarik/batik yang di-wiru (lipatan) menunjukkan ketelitian dan kesabaran.',
    konteks: 'Dipakai untuk acara formal, upacara pernikahan (siraman, midodareni), upacara adat keraton, dan sebagai salah satu busana resmi nasional Indonesia.',
  },
  {
    id: 'betawi',
    name: 'Pangsi Betawi',
    origin: 'DKI Jakarta',
    description: 'Pakaian khas kaum lelaki Betawi yang melambangkan kebebasan bergerak dan kesederhanaan.',
    imageUrl: '/assets/wastra-betawi.png',
    coordinates: { lat: -6.2, lng: 106.81 },
    sejarah: 'Pakaian ini identik dengan para "Jawara" atau pendekar silat Betawi. Desainnya yang longgar (Baju Pangsi) dan celana (celana Pangsi) dirancang untuk keleluasaan dalam bergerak.',
    filosofi: 'Desain longgar melambangkan kebebasan, kejujuran, dan keterbukaan. Warna-warna gelap (hitam atau merah) sering dikaitkan dengan para jawara yang tangguh. Pakaian ini juga mencerminkan kesederhanaan dan identitas rakyat jelata.',
    konteks: 'Dulu pakaian sehari-hari, kini dipakai untuk acara budaya Betawi (misal Palang Pintu), pertunjukan silat, dan acara formal kedaerahan. Peci merah melambangkan keberanian.',
  },
  {
    id: 'sunda',
    name: 'Kebaya Sunda',
    origin: 'Jawa Barat',
    description: 'Kebaya Sunda dikenal dengan desainnya yang elegan dan pas di badan, sering dipadukan dengan kain batik corak Sunda.',
    imageUrl: '/assets/wastra-sunda.png',
    coordinates: { lat: -6.91, lng: 107.61 },
    sejarah: 'Memiliki akar yang sama dengan kebaya Jawa, namun berkembang dengan ciri khasnya sendiri. Kebaya Sunda modern banyak dipengaruhi oleh desain Eropa (Belanda) pada masa kolonial, terutama di kalangan bangsawan Priangan.',
    filosofi: 'Kebaya Sunda menonjolkan keanggunan dan keeleganan wanita Pasundan. Ciri khasnya adalah kerah berbentuk U (U-neck) dan desain yang pas di badan, melambangkan wanita yang rapi, tertib, dan menghargai keindahan.',
    konteks: 'Sering digunakan untuk acara pernikahan (terutama resepsi), upacara adat Sunda, pelantikan, dan acara formal lainnya. Sering dipadukan dengan sanggul \'Ciwidey\' atau \'Pasundan\'.',
  },
  {
    id: 'madura',
    name: 'Pesa\'an Madura',
    origin: 'Jawa Timur',
    description: 'Busana pria Madura dengan kaos bergaris merah-putih dan celana gombrong, melambangkan keberanian dan semangat juang.',
    imageUrl: '/assets/wastra-madura.png',
    coordinates: { lat: -7.0, lng: 113.5 },
    sejarah: 'Ini adalah pakaian sehari-hari rakyat jelata, terutama para nelayan dan petani. Desainnya yang praktis dan longgar memudahkan mereka saat bekerja.',
    filosofi: 'Kaos bergaris merah-putih melambangkan keberanian (merah) dan kesucian/kejujuran (putih). Celana gombrong (disebut juga "Komboran") melambangkan kebebasan dan kesederhanaan. Udeng (ikat kepala) dan sabuk adalah pelengkap yang menunjukkan kewibawaan.',
    konteks: 'Meskipun dulu pakaian kerja, kini Baju Pesa\'an menjadi identitas budaya Madura. Dipakai dalam acara adat, festival, dan terutama dalam tradisi Karapan Sapi.',
  },
  {
    id: 'aceh',
    name: 'Ulee Balang',
    origin: 'Aceh',
    description: 'Pakaian kebesaran bangsawan Aceh, sarat dengan sulaman benang emas yang menunjukkan kemewahan dan status sosial.',
    imageUrl: '/assets/wastra-aceh.png',
    coordinates: { lat: 5.55, lng: 95.32 },
    sejarah: 'Pakaian ini awalnya hanya boleh dikenakan oleh keluarga bangsawan (Ulee Balang) dan Sultan pada masa Kesultanan Aceh. Pakaian pria disebut Linto Baro, dan wanita disebut Daro Baro.',
    filosofi: 'Setiap elemen mencerminkan nilai Islam dan adat. Sulaman emas (disebut "kasab") melambangkan kemakmuran dan kejayaan. Warna hitam melambangkan kebesaran dan ketegasan. Rencong (senjata) yang diselipkan adalah simbol keberanian dan identitas rakyat Aceh.',
    konteks: 'Saat ini, pakaian Ulee Balang menjadi busana wajib untuk upacara pernikahan adat Aceh. Juga dipakai dalam upacara penyambutan tamu penting dan festival budaya.',
  },
  {
    id: 'lampung',
    name: 'Tulang Bawang',
    origin: 'Lampung',
    description: 'Pakaian adat Lampung yang menggunakan kain tapis, kain tenun khas yang disulam dengan benang emas atau perak.',
    imageUrl: '/assets/wastra-lampung.png',
    coordinates: { lat: -4.55, lng: 105.4 },
    sejarah: 'Kain Tapis adalah kain tenun tradisional Lampung yang dibuat oleh wanita secara turun-temurun. Pakaian adat ini (Siger Pengunten) merupakan evolusi dari tradisi kuno yang menggabungkan pengaruh Hindu-Buddha dan Islam.',
    filosofi: 'Siger (mahkota wanita) dengan 9 lekukan melambangkan 9 sungai besar di Lampung dan identitas wanita. Kain Tapis yang disulam benang emas melambangkan kemewahan, status sosial, dan sebagai "simpanan" kekayaan keluarga.',
    konteks: 'Pakaian adat ini, terutama Siger Pengunten dan Kain Tapis, adalah busana wajib dalam prosesi pernikahan adat Lampung (Pepadun dan Saibatin).',
  },
  {
    id: 'riau',
    name: 'Teluk Belanga',
    origin: 'Riau',
    description: 'Baju kurung longgar untuk pria dan wanita Melayu, mencerminkan nilai-nilai kesopanan dan keislaman.',
    imageUrl: '/assets/wastra-riau.png',
    coordinates: { lat: 0.5, lng: 101.44 },
    sejarah: 'Merupakan pakaian tradisional orang Melayu di Riau, Kepulauan Riau, dan Malaysia. Teluk Belanga (untuk pria) dan Baju Kurung (untuk wanita) telah menjadi busana standar selama berabad-abad.',
    filosofi: 'Desain yang longgar dan tidak membentuk tubuh mencerminkan nilai-nilai Islam (menutup aurat) dan adat Melayu ("adat bersendi syarak, syarak bersendi kitabullah"). Kesopanan adalah kunci utama dari busana ini.',
    konteks: 'Dipakai untuk acara formal, keagamaan (salat Jumat, Lebaran), pernikahan, dan sebagai pakaian sehari-hari di lingkungan yang masih kental adatnya.',
  },
  {
    id: 'jambi',
    name: 'Baju Kurung Tanggung',
    origin: 'Jambi',
    description: 'Baju kurung khas Jambi yang panjang lengannya tanggung (tiga perempat), sering dihiasi sulaman emas.',
    imageUrl: '/assets/wastra-jambi.png',
    coordinates: { lat: -1.61, lng: 103.61 },
    sejarah: 'Busana ini merupakan pakaian adat resmi Jambi yang sering dipadukan dengan kain songket Jambi yang kaya motif. Desain "tanggung" (tanggung) pada lengan adalah ciri khasnya.',
    filosofi: 'Lengan yang "tanggung" (tidak panjang, tidak pendek) melambangkan sifat wanita Jambi yang cekatan, rajin, dan fleksibel. Sulaman emas pada bagian dada dan lengan melambangkan kekayaan alam Jambi, terutama emas.',
    konteks: 'Umumnya digunakan oleh wanita untuk upacara adat, pernikahan, penyambutan tamu, dan acara-acara resmi pemerintahan di Jambi.',
  },
  {
    id: 'bangkabelitung',
    name: 'Paksian',
    origin: 'Bangka Belitung',
    description: 'Pakaian pengantin wanita yang terinspirasi dari busana Tionghoa, menunjukkan akulturasi budaya di Bangka Belitung.',
    imageUrl: '/assets/wastra-bangkabelitung.png',
    coordinates: { lat: -2.74, lng: 106.44 },
    sejarah: 'Pakaian Paksian (untuk wanita) dan Baju Seting (untuk pria) adalah hasil akulturasi budaya yang kental antara budaya Melayu (Arab) dan Tionghoa. Ini mencerminkan sejarah Bangka Belitung sebagai jalur perdagangan yang ramai.',
    filosofi: 'Warna merah dan hiasan keemasan menunjukkan pengaruh kuat budaya Tionghoa yang melambangkan keberuntungan dan kemakmuran. Mahkota (Paksian) pada wanita adalah simbol keanggunan.',
    konteks: 'Pakaian ini adalah busana pengantin khas Bangka Belitung yang wajib dikenakan saat upacara pernikahan adat.',
  },
  {
    id: 'banten',
    name: 'Baju Pangsi Banten',
    origin: 'Banten',
    description: 'Pakaian sederhana masyarakat Baduy dan Banten, melambangkan kesahajaan dan kedekatan dengan alam.',
    imageUrl: '/assets/wastra-banten.png',
    coordinates: { lat: -6.4, lng: 106.06 },
    sejarah: 'Pangsi adalah pakaian sehari-hari masyarakat agraris di Banten, terutama di kalangan Suku Baduy (Kanekes). Pakaian ini dirancang untuk kesederhanaan dan fungsionalitas.',
    filosofi: 'Bagi Suku Baduy Dalam, warna putih (Kutang) melambangkan kesucian dan tidak boleh diwarnai. Bagi Baduy Luar dan masyarakat Banten pada umumnya, warna hitam melambangkan kesahajaan dan "kembali ke tanah". Desainnya yang simpel adalah simbol hidup yang apa adanya.',
    konteks: 'Pakaian sehari-hari bagi Suku Baduy. Bagi masyarakat Banten modern, Pangsi sering dipakai dalam acara adat, festival budaya, dan sebagai simbol identitas kedaerahan.',
  },
  {
    id: 'yogyakarta',
    name: 'Kasatrian Ageng',
    origin: 'Yogyakarta',
    description: 'Busana kebesaran pria di Keraton Yogyakarta, terdiri dari kain batik, surjan, dan blangkon dengan corak khas.',
    imageUrl: '/assets/wastra-yogyakarta.png',
    coordinates: { lat: -7.79, lng: 110.36 },
    sejarah: 'Ini adalah salah satu busana kebesaran yang dipakai oleh Sultan dan kerabat pria di lingkungan Keraton Ngayogyakarta Hadiningrat, diwariskan sejak era Hamengku Buwono I.',
    filosofi: 'Surjan (baju atasan) dengan motif lurik (garis) melambangkan kesederhanaan dan kesetiaan. Blangkon (ikat kepala) dengan "mondolan" di belakang adalah simbol kecerdasan dan kerendahan hati. Kain batik corak "parang" (yang sering dipakai) melambangkan kekuasaan dan pantang menyerah.',
    konteks: 'Dikenakan untuk upacara-upacara agung di dalam Keraton, seperti Grebeg, penobatan, atau pisowanan (menghadap Sultan). Pakaian ini sangat sakral dan memiliki aturan pemakaian yang ketat.',
  },
  {
    id: 'kaltara',
    name: 'Ta\'a & Sapei Sapaq',
    origin: 'Kalimantan Utara',
    description: 'Pakaian wanita (Ta\'a) dan pria (Sapei Sapaq) dari Dayak Kenyah, dihiasi manik-manik dan taring macan.',
    imageUrl: '/assets/wastra-kaltara.png',
    coordinates: { lat: 3.0, lng: 116.0 },
    sejarah: 'Ini adalah pakaian adat Suku Dayak Kenyah yang mendiami wilayah Kalimantan Utara dan Timur. Pakaian ini mencerminkan tradisi lisan dan seni ukir yang kaya dari suku tersebut.',
    filosofi: 'Ta\'a (untuk wanita) dan Sapei Sapaq (untuk pria) dihiasi dengan motif-motif yang memiliki kekuatan magis. Bulu enggang di kepala melambangkan kebesaran, taring macan/beruang menunjukkan keberanian, dan manik-manik berwarna-warni melambangkan keindahan alam.',
    konteks: 'Digunakan untuk upacara adat besar, tarian penyambutan (seperti Tari Kancet), upacara pernikahan, dan ritual-ritual komunal lainnya.',
  },
  {
    id: 'gorontalo',
    name: 'Biliu & Makuta',
    origin: 'Gorontalo',
    description: 'Pakaian pengantin Gorontalo (Biliu untuk wanita, Makuta untuk pria) yang sarat dengan hiasan keemasan.',
    imageUrl: '/assets/wastra-gorontalo.png',
    coordinates: { lat: 0.54, lng: 123.05 },
    sejarah: 'Pakaian ini adalah busana pengantin tradisional Gorontalo yang telah diwariskan dari zaman kerajaan-kerajaan kuno di Gorontalo.',
    filosofi: 'Pakaian ini melambangkan kemegahan dan status. Biliu (mahkota wanita) dan Makuta (mahkota pria) adalah simbol raja dan ratu sehari. Hiasan-hiasan keemasan melambangkan kemakmuran, dan setiap detail memiliki makna adat yang mendalam (misal, jumlah hiasan di dada).',
    konteks: 'Busana ini adalah pakaian wajib untuk kedua mempelai dalam upacara pernikahan adat Gorontalo, yang prosesinya bisa berlangsung berhari-hari.',
  },
  {
    id: 'sulut',
    name: 'Laku Tepu',
    origin: 'Sulawesi Utara',
    description: 'Pakaian adat dari Sangihe Talaud yang terbuat dari serat tanaman pisang abaka, berbentuk terusan panjang.',
    imageUrl: '/assets/wastra-sulut.png',
    coordinates: { lat: 1.48, lng: 124.84 },
    sejarah: 'Laku Tepu adalah pakaian kuno dari Suku Sangihe-Talaud (wilayah kepulauan di utara Sulawesi). Pakaian ini unik karena bahan dasarnya adalah serat pelepah pisang abaka (disebut "kofo" atau "koffo").',
    filosofi: 'Pakaian ini menunjukkan kecerdasan masyarakat Sangihe dalam memanfaatkan alam. Bentuknya yang sederhana (terusan) melambangkan kesahajaan. Hiasan kepala (paporong) adalah pelengkap yang menunjukkan status.',
    konteks: 'Dulu dipakai untuk acara adat dan upacara keagamaan. Saat ini, Laku Tepu sering ditampilkan kembali dalam festival budaya dan tarian adat untuk melestarikan tradisi.',
  },
  {
    id: 'sulteng',
    name: 'Baju Nggembe',
    origin: 'Sulawesi Tengah',
    description: 'Baju adat untuk remaja putri Kaili, berbentuk segi empat dengan hiasan manik-manik di bagian leher.',
    imageUrl: '/assets/wastra-sulteng.png',
    coordinates: { lat: -0.9, lng: 119.86 },
    sejarah: 'Baju Nggembe adalah pakaian tradisional Suku Kaili yang mendiami lembah Palu. Ini adalah pakaian adat yang khusus dikenakan oleh remaja putri.',
    filosofi: 'Bentuknya yang longgar dan tidak berjahit di sisi (hanya lubang kepala dan lengan) melambangkan kesederhanaan dan kesucian gadis yang belum menikah. Hiasan di leher (disebut "gemo") adalah simbol keindahan.',
    konteks: 'Digunakan oleh remaja putri saat upacara adat, festival, atau tarian tradisional. Pakaian ini menandakan bahwa pemakainya adalah seorang gadis yang memasuki masa dewasa.',
  },
  {
    id: 'sulbar',
    name: 'Pattuqduq Towaine',
    origin: 'Sulawesi Barat',
    description: 'Busana penari wanita Mandar, terdiri dari baju kurung, lipa\' saqbe (sarung sutra), dan hiasan kepala yang khas.',
    imageUrl: '/assets/wastra-sulbar.png',
    coordinates: { lat: -2.67, lng: 118.86 },
    sejarah: 'Pattuqduq Towaine adalah busana untuk penari Tarian Pattuqduq dari Suku Mandar. Tarian ini awalnya ditarikan di istana untuk menyambut tamu agung atau merayakan kemenangan.',
    filosofi: 'Busana ini melambangkan kelembutan namun juga ketangkasan wanita Mandar. Lipa\' Saqbe (sarung sutra) dengan motif khas Mandar menunjukkan keahlian menenun. Hiasan kepala yang menjulang adalah simbol keanggunan.',
    konteks: 'Saat ini, pakaian ini identik dengan penari Pattuqduq. Tarian dan busana ini ditampilkan dalam upacara penyambutan, festival budaya, dan acara pernikahan.',
  },
  {
    id: 'sultra',
    name: 'Babu Nggawi',
    origin: 'Sulawesi Tenggara',
    description: 'Pakaian adat suku Tolaki untuk wanita, terdiri dari blus dan sarung tenun dengan corak gemerlap.',
    imageUrl: '/assets/wastra-sultra.png',
    coordinates: { lat: -3.98, lng: 122.51 },
    sejarah: 'Babu Nggawi adalah pakaian adat kebesaran Suku Tolaki, salah satu suku terbesar di Sulawesi Tenggara. Pakaian ini diwariskan dari zaman kerajaan-kerajaan Tolaki.',
    filosofi: 'Pakaian ini (Babu Nggawi untuk wanita, Babu Nggawi Langgai untuk pria) melambangkan status sosial dan keagungan. Warna-warna cerah dan penggunaan benang emas atau perak pada tenunan melambangkan kemakmuran dan martabat.',
    konteks: 'Digunakan untuk upacara-upacara kebesaran adat, terutama upacara pernikahan, pelantikan pemangku adat, dan upacara penyambutan tamu kerajaan.',
  },
  {
    id: 'ntb',
    name: 'Baju Lambung',
    origin: 'Nusa Tenggara Barat',
    description: 'Pakaian adat suku Sasak di Lombok, berupa baju hitam tanpa lengan dengan hiasan di bagian dada.',
    imageUrl: '/assets/wastra-ntb.png',
    coordinates: { lat: -8.58, lng: 116.11 },
    sejarah: 'Baju Lambung adalah pakaian tradisional wanita Suku Sasak di Lombok. Pakaian ini telah ada sejak lama dan menjadi bagian dari pakaian sehari-hari wanita Sasak di masa lalu.',
    filosofi: 'Warna hitam pada baju melambangkan kesederhanaan dan kepatuhan. Hiasan manik-manik dan cermin di bagian dada (kerah) adalah simbol keindahan dan juga berfungsi sebagai penolak bala.',
    konteks: 'Saat ini, Baju Lambung tidak lagi dipakai sehari-hari, namun wajib dikenakan dalam upacara adat, tarian penyambutan (seperti Tari Gendang Beleq), dan saat prosesi "Bau Nyale" (festival cacing laut).',
  },
  {
    id: 'ntt',
    name: 'Pakaian Adat Rote',
    origin: 'Nusa Tenggara Timur',
    description: 'Dikenal dengan topi khas Ti\'i langga untuk pria, dan kain tenun ikat yang kaya motif untuk wanita.',
    imageUrl: '/assets/wastra-ntt.png',
    coordinates: { lat: -10.5, lng: 123.0 },
    sejarah: 'Pakaian ini adalah cerminan budaya Suku Rote. Ciri paling khas, Ti\'i Langga (topi pria), terinspirasi dari daun lontar yang menjadi sumber kehidupan utama di Pulau Rote.',
    filosofi: 'Ti\'i Langga (topi) melambangkan kewibawaan dan kepemimpinan. Kain tenun ikat Rote dengan motif geometris yang rumit (seperti motif "buna") adalah simbol status sosial, keterampilan menenun, dan sebagai media pencatat sejarah keluarga.',
    konteks: 'Pakaian lengkap ini dikenakan saat upacara adat, pernikahan, upacara kematian, dan festival budaya. Ti\'i Langga kini juga menjadi ikon budaya NTT.',
  },
  {
    id: 'maluku',
    name: 'Baju Cele',
    origin: 'Maluku',
    description: 'Kain kebaya yang dipadukan dengan sarung tenun, memiliki corak kotak-kotak kecil yang khas.',
    imageUrl: '/assets/wastra-maluku.png',
    coordinates: { lat: -3.69, lng: 128.18 },
    sejarah: 'Baju Cele (atau "Kain Salele") adalah busana yang umum dipakai di Maluku, terutama Ambon. Dipengaruhi oleh busana Eropa (Portugis dan Belanda) yang dipadukan dengan kain tenun lokal.',
    filosofi: 'Motif kotak-kotak kecil atau garis-garis pada kain melambangkan kesederhanaan dan persatuan masyarakat. Warna-warna cerah (merah, kuning) sering dipilih untuk melambangkan keceriaan dan semangat orang Maluku.',
    konteks: 'Dipakai untuk acara-acara penting, terutama upacara keagamaan (Gereja), pesta adat, pernikahan, dan tarian tradisional seperti Tari Katreji.',
  },
];